remote_theme: LinuxSuRen/minimal@v0.0.1
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
# theme: jekyll-theme-minimal
title: guo.ph
logo: photo.jpeg
show_downloads: false
google_analytics: G-WF6DD5W01G
