collections:
  redirects:
    output: true
remote_theme: LinuxSuRen/minimal@v0.0.1
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-scholar
scholar:
  style: apa
  locale: en
  sort_by: year, month
  order: descending
  # --- 自动生成详情页的核心配置 ---
  details_dir:    pub
  details_layout: bib.html
  details_link:   "[Details & Abstract]"
  bibliography:   pub/papers.bib
  use_raw_bibtex_entry_as_source: true
# theme: jekyll-theme-minimal
title: guo.ph
logo: photo.jpeg
show_downloads: false
google_analytics: G-WF6DD5W01G
